# Generated by Django 4.0.6 on 2022-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScalarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('scalarToken', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
