# Generated by Django 4.0.6 on 2022-07-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0002_scalartoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalartoken',
            name='sytToken',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
