# Generated by Django 4.0.6 on 2022-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0003_scalartoken_syttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
