# Generated by Django 4.0.6 on 2022-07-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0004_widget_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='slug',
        ),
    ]
