# Generated by Django 4.0.6 on 2022-07-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widget', '0005_remove_widget_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
